spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagement
spring.datasource.username=postgres
spring.datasource.password=laithosama0418postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=public
spring.flyway.schemas=public

logging.level.org.flywaydb=debug
logging.level.org.springframework.boot.autoconfigure.flyway=debug

logging.level.org.springframework.web=debug
logging.level.org.springframework.web.servlet.mvc.method.annotation=debug
logging.level.com.laith.taskmanagement=debug



jwt.secret=CHANGE_ME_TO_32+_CHARS_SECRET_KEY_!!!!!!!!
jwt.expiration-seconds=3600
jwt.issuer=task-management-api


#spring.security.user.name=laith
#spring.security.user.password=0000
#spring.security.user.roles=ADMIN,USER